version: 2

build: 
  image: latest

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

formats: []
